### PR TITLE
Add libgmp-dev package

### PR DESCRIPTION
**Pull request by Amit-PivotalLabs**
This lets bosh_kubernetes_cpi package compile on any stemcell

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Think that @CLAassistant might not be working?

**Comment by loewenstein** [comment]
@Amit-PivotalLabs If I click on the banner I get to the CLA that should be signed. What do you see?

**Comment by Amit-PivotalLabs** [comment]
It briefly says "Please sign the...." and then says "You have signed the CLA for SAP/bosh-kubernetes-cpi-release"

screen shot 2017-07-06 at 2 01 59 am

**Comment by Amit-PivotalLabs** [comment]
I'm pretty sure I've now signed the CLA as both @Amit-PivotalLabs and @amitkgupta.  Tried hitting "recheck it" to no avail.

**Comment by loewenstein** [comment]
I will check with @CLAassistant what is at odds here.

**Comment by matz3** [comment]
@amitkgupta is not showing up as a contributor in CLA assistant.
Could you please make sure to logon to GitHub with that user and click on the "Sign" badge in this PR?

**Comment by loewenstein** [comment]
Hi Amit,

I suspect you where still logged in (with CLA assistant) with your other account.

Could you please try the following:
- Open https://cla-assistant.io
- Sign in / sign out
- Sign the CLA with @amitkgupta

**Comment by Amit-PivotalLabs** [comment]
Hi all,

I definitely logged out of GH, logged in as @amitkgupta, then clicked the
CLA badge. The screenshots I sent you separately showed that Jan. Are you
saying the authentication for the CLA assistant was still stuck on my
Amit-PivotalLabs account?

When I follow the link below on my phone, and log in as amitkgupta, it has
me go through the oauth flow, agreeing to different permissions, etc. It's
asking for read/write permissions on things like my gists, my repos'
webhooks, etc. Is that normal?

Thanks,
Amit

**Comment by loewenstein** [comment]
I know you logged out of GH. And yes I suspect @CLAassistant still has you logged in. Maybe instead of granting all those permissions you find the right cookie to delete or go for an inkognito session? 

The additional  permissions are for using the service on one of your repos. But again with an incognito session to sign cla this should not be necessary.

**Pull request merged**
